#!/usr/bin/env python3
"""文章页 / 目录页后处理（book-teardown）。

把 skill 模板生成的裸 HTML 补成站点标准形态，共 6 项：
  1. 顶栏 brand-dot -> 书形图标（+ sprite 追加 i-github / i-book）
  2. 顶栏右侧 GitHub 按钮
  3. favicon / apple-touch-icon 链接
  4. 返回链接：文章页「← 返回《书名》系列目录」(+ NAV-INJECT 样式)，
     目录页「← 返回书籍总目录」（back-home CSS 内联进目录页 <style>）
  5. 页脚「Generated by md2html」->「↑ 回到顶部」
  6. SEO：description / canonical / OG / Twitter / JSON-LD（SEO-INJECT 块），
     新 URL 追加进 sitemap.xml，根 index.html 的 JSON-LD 书目刷新

用法：
    python3 tools/postprocess.py                                  # 补全部书目录
    python3 tools/postprocess.py 黑天鹅                           # 补一本书
    python3 tools/postprocess.py 黑天鹅 反脆弱 非对称风险 双城记    # 补多本
    python3 tools/postprocess.py --check                          # 只检查缺什么，不写盘
    BASE_URL=https://books.example.com python3 tools/postprocess.py

处理完书目录后自动做站点级同步：
  - sitemap.xml 追加新 URL
  - 根 index.html：JSON-LD 书目刷新 + 缺卡的书自动补卡片
    （分类/卡片文案映射见 tools/books.json；缺省简介取 00 的「系列简介」第一段，
    未配分类的书放到最后一部分并告警）+ 卡号重排 + 「N 本书 · M 篇」统计
  - README.md：计数与「收录书籍」分类表同步重建

幂等：每项先检测已存在则跳过，可反复跑；跑完打印 changed/skipped 明细。
"""
import argparse
import json
import re
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parent
sys.path.insert(0, str(TOOLS))
import seo as S  # noqa: E402

S.ROOT = ROOT

DESC_MASTER = ("书籍深度解读合集：每本书一个系列，先拆解全书结构与知识地图，"
               "再逐篇回答一个核心问题，区分观点、事实与争议。")

BRAND_OLD = '        <span class="brand-dot" aria-hidden="true"></span>\n'
BRAND_NEW = ('        <svg class="icon" viewBox="0 0 24 24" width="18" height="18" '
             'style="color:var(--accent)" aria-hidden="true"><use href="#i-book"/></svg>\n')
GITHUB_BTN = ('        <a class="icon-btn" href="https://github.com/davidzhanghui/book-teardown" '
              'target="_blank" rel="noopener" title="GitHub 仓库" aria-label="GitHub 仓库">\n'
              '          <svg class="icon" viewBox="0 0 24 24" aria-hidden="true">'
              '<use href="#i-github"/></svg>\n'
              '        </a>\n\n')
PRINT_BTN = '        <button class="icon-btn" onclick="window.print()"'
FOOTER_OLD = '<span>Generated by <a href="#">md2html</a></span>'
FOOTER_NEW = '<span><a href="#top">↑ 回到顶部</a></span>'
LINK_LINE = ('    <symbol id="i-link" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
             'stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
             '<path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/>'
             '<path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></symbol>\n')
SYM_GITHUB = ('      <symbol id="i-github" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
              'stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
              '<path fill="currentColor" stroke="none" d="M12 .297c-6.63 0-12 5.373-12 12 0 5.303 3.438 9.8 '
              '8.205 11.385.6.113.82-.258.82-.577 0-.285-.01-1.04-.015-2.04-3.338.724-4.042-1.61-4.042-1.61'
              'C4.422 18.07 3.633 17.7 3.633 17.7c-1.087-.744.084-.729.084-.729 1.205.084 1.838 1.236 1.838 '
              '1.236 1.07 1.835 2.809 1.305 3.495.998.108-.776.417-1.305.76-1.605-2.665-.3-5.466-1.332-5.466'
              '-5.93 0-1.31.465-2.38 1.235-3.22-.135-.303-.54-1.523.105-3.176 0 0 1.005-.322 3.3 1.23.96-.267 '
              '1.98-.399 3-.405 1.02.006 2.04.138 3 .405 2.28-1.552 3.285-1.23 3.285-1.23.645 1.653.24 2.873.12 '
              '3.176.765.84 1.23 1.91 1.23 3.22 0 4.61-2.805 5.625-5.475 5.92.42.36.81 1.096.81 2.22 0 1.606'
              '-.015 2.896-.015 3.286 0 .315.21.69.825.57C20.565 22.092 24 17.592 24 12.297c0-6.627-5.373-12-12-12"/>'
              '</symbol>\n')
SYM_BOOK = ('      <symbol id="i-book" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            'stroke-width="2" stroke-linecap="round" stroke-linejoin="round">'
            '<path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z"/>'
            '<path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z"/></symbol>\n')
SYMS = SYM_GITHUB + SYM_BOOK
NAV = ('<!-- NAV-INJECT:START -->\n'
       '<style>\n'
       '  .doc-header .back-home { display: table;\n'
       '    margin-bottom: 14px; padding: 4px 12px; font-size: 13px; font-weight: 500;\n'
       '    color: var(--accent-strong); text-decoration: none;\n'
       '    background: var(--accent-soft); border: 1px solid var(--accent-border);\n'
       '    border-bottom: 1px solid var(--accent-border); border-radius: 999px;\n'
       '    transition: color .15s, border-color .15s; }\n'
       '  .doc-header .back-home:hover { color: var(--accent-hover);\n'
       '    border-color: var(--accent); border-bottom-color: var(--accent); }\n'
       '</style>\n'
       '<!-- NAV-INJECT:END -->\n')
FAVICON = ('  <link rel="icon" type="image/svg+xml" href="../assets/icon.svg">\n'
           '  <link rel="icon" type="image/png" sizes="32x32" href="../assets/favicon-32.png">\n'
           '  <link rel="apple-touch-icon" href="../assets/apple-touch-icon.png">\n')
IDX_ANCHOR = ('      .idx-title { color: var(--text); font-size: 15px; '
              'font-weight: 500; line-height: 1.45; }\n')
IDX_EXTRA = ('\n'
             '      .doc-header .back-home { display: table;\n'
             '        margin-bottom: 14px; padding: 4px 12px; font-size: 13px; font-weight: 500;\n'
             '        color: var(--accent-strong); text-decoration: none;\n'
             '        background: var(--accent-soft); border: 1px solid var(--accent-border);\n'
             '        border-bottom: 1px solid var(--accent-border); border-radius: 999px;\n'
             '        transition: color .15s, border-color .15s; }\n'
             '      .doc-header .back-home:hover { color: var(--accent-hover);\n'
             '        border-color: var(--accent); border-bottom-color: var(--accent); }\n')


def head_anchor(h):
    """找 </head> 前最后一个 </style>，返回从该行首到 </head> 的整段。

    favicon 插入的是 <link> 行、back-home(文章页)插入的是 NAV <style> 块，
    都会落在主 </style> 之后。所以锚点必须动态定位最后一个 </style>，
    不能写死 "  </style>\\n</head>" 这类常量（目录页缩进还不一样）。
    """
    i = h.rfind("</style>")
    assert i != -1
    ls = h.rfind("\n", 0, i) + 1
    style_indent = h[ls:i]
    assert style_indent.strip() == "", repr(style_indent)
    j = h.index("</head>", i)
    anchor = h[ls:j + len("</head>")]
    assert h.count(anchor) == 1, repr(anchor[-80:])
    return anchor


def split_head(h, anchor):
    style_indent = anchor.split("</style>")[0]
    head_indent = anchor.split("\n")[-1].split("</head>")[0]
    return style_indent, head_indent
DOC_HEADER = '      <header class="doc-header">\n'

ITEMS = ("brand", "github-btn", "favicon", "back-home", "footer", "seo")


def doc_date(html):
    m = re.search(r"更新于 (\d{4}-\d{2}-\d{2})", html)
    return m.group(1) if m else "2026-09-20"


def need(h, item, is_index):
    """该文件是否还缺这一项。"""
    if item == "brand":
        return BRAND_OLD in h
    if item == "github-btn":
        return "github.com/davidzhanghui" not in h
    if item == "favicon":
        return "assets/icon.svg" not in h
    if item == "back-home":
        return "back-home" not in h
    if item == "footer":
        return FOOTER_OLD in h
    if item == "seo":
        return S.MARK_S not in h
    raise ValueError(item)


def apply(h, item, book, is_index):
    if item == "brand":
        assert h.count(BRAND_OLD) == 1
        return h.replace(BRAND_OLD, BRAND_NEW)
    if item == "github-btn":
        assert h.count(LINK_LINE) == 1
        h = h.replace(LINK_LINE, LINK_LINE + SYMS)
        assert h.count(PRINT_BTN) == 1
        return h.replace(PRINT_BTN, GITHUB_BTN + PRINT_BTN)
    if item == "favicon":
        anchor = head_anchor(h)
        style_indent, head_indent = split_head(h, anchor)
        tails = [ln for ln in FAVICON.rstrip("\n").split("\n")]
        block = "\n".join(style_indent + ln if ln.strip() else ln for ln in tails) + "\n"
        new_tail = style_indent + "</style>\n" + block + head_indent + "</head>"
        assert anchor.endswith("</head>")
        return h.replace(anchor, new_tail)
    if item == "back-home":
        if is_index:
            assert IDX_ANCHOR in h
            h = h.replace(IDX_ANCHOR, IDX_ANCHOR + IDX_EXTRA)
            link = ('      <a class="back-home" href="../index.html">← 返回书籍总目录</a>\n\n')
            assert h.count(DOC_HEADER) == 1
            return h.replace(DOC_HEADER, DOC_HEADER + link)
        link = (f'      <a class="back-home" href="index.html">← 返回《{book}》系列目录</a>\n\n')
        assert h.count(DOC_HEADER) == 1
        h = h.replace(DOC_HEADER, DOC_HEADER + link)
        anchor = head_anchor(h)
        style_indent, _ = split_head(h, anchor)
        nav = "\n".join((style_indent + ln if ln.strip() else ln)
                        for ln in NAV.rstrip("\n").split("\n")) + "\n"
        inner = anchor[:anchor.index("</head>")]
        return h.replace(anchor, inner + nav + anchor[len(inner):])
    if item == "footer":
        assert FOOTER_OLD in h
        return h.replace(FOOTER_OLD, FOOTER_NEW)
    raise ValueError(item)


def apply_seo(h, rel, kind, book, bdesc, date, ld):
    """SEO 块插到 </head> 前。文章页顺序固定：NAV 样式 -> SEO 块 -> favicon。

    注意：need() 用 "back-home" 字符串判断 NAV 样式是否缺失，
    所以 back-home 链接插入时必须连 NAV 样式一起落盘。
    """
    block = S.build_block(rel, kind, S.page_title(h) or book, bdesc or "", date, ld) + "\n"
    anchor = head_anchor(h)
    style_indent, head_indent = split_head(h, anchor)
    block = "\n".join((style_indent + ln if ln.strip() else ln)
                       for ln in block.rstrip("\n").split("\n")) + "\n"
    if kind == "collection" and rel.name == "index.html":
        # 目录页顺序（与旧书一致）：SEO 块 -> favicon。
        # favicon 步骤先插了 favicon，这里把 SEO 块插到 favicon 之前。
        fav_lines = [ln for ln in FAVICON.rstrip("\n").split("\n")]
        first_fav = style_indent + fav_lines[0]
        if first_fav in h:
            for ln in fav_lines:
                h = h.replace(style_indent + ln + "\n", "", 1)
            anchor = head_anchor(h)
            style_indent, head_indent = split_head(h, anchor)
            block = "\n".join((style_indent + ln if ln.strip() else ln)
                               for ln in block.rstrip("\n").split("\n")) + "\n"
            fav_block = "\n".join(style_indent + ln for ln in fav_lines)
            new_tail = (style_indent + "</style>\n" + block.rstrip("\n")
                        + "\n" + fav_block + "\n" + head_indent + "</head>")
            return h.replace(anchor, new_tail)
        new_tail = style_indent + "</style>\n" + block + head_indent + "</head>"
        return h.replace(anchor, new_tail)
    assert "<!-- NAV-INJECT:START -->" in h, "文章页先做 back-home 再做 seo"
    assert "assets/icon.svg" in h, "文章页先做 favicon 再做 seo"
    nav_end = style_indent + "<!-- NAV-INJECT:END -->"
    assert nav_end in h
    # 标准顺序（与旧书一致）：NAV 样式 -> SEO 块 -> favicon。
    # back-home 步骤把 NAV 插在 head 尾（favicon 之后），SEO 块先跟在
    # NAV 后面，最后把 favicon 三行搬到 SEO 块之后，还原旧书顺序。
    fav_lines = [ln for ln in FAVICON.rstrip("\n").split("\n")]
    first_fav = style_indent + fav_lines[0]
    assert first_fav in h, "favicon 应已由 favicon 步骤插入"
    block = "\n".join((style_indent + ln if ln.strip() else ln)
                       for ln in block.rstrip("\n").split("\n")) + "\n"
    h = h.replace(nav_end, nav_end + "\n" + block.rstrip("\n"), 1)
    for ln in fav_lines:
        h = h.replace(style_indent + ln + "\n", "", 1)
    fav_block = "\n".join(style_indent + ln for ln in fav_lines)
    anchor2 = head_anchor(h)
    inner2 = anchor2[:anchor2.index("</head>")]
    inner3 = inner2.rstrip("\n") + "\n" + fav_block + "\n"
    tail = anchor2[len(inner2):]
    return h.replace(anchor2, inner3 + tail)


def seo_desc(h, bdesc):
    return S.truncate(S.first_para(h)) or bdesc


# ---------------------------------------------------------------- 总目录卡片 / README 同步
CATS_CONF = TOOLS / "books.json"

CARD_T = ('<a class="book-card" href="{dir}/index.html">\n'
          '  <span class="card-top"><span class="card-num">{num}</span>'
          '<span class="stars">{n} 篇</span></span>\n'
          '  <span class="card-title">《{title}》</span>\n'
          '  <span class="card-q">{desc}</span>\n'
          '  <span class="card-go">进入系列 →</span>\n'
          '</a>\n')

# <div class="part-head"><span class="part-no">第N部分</span><h2 id="gN">名称</h2></div>
# <div class="card-grid"> ...cards... </div>   （卡片内无 div，可直接非贪婪匹配）
PART_RE = re.compile(
    r'<div class="part-head"><span class="part-no">([^<]*)</span>'
    r'<h2 id="g\d+">([^<]*)</h2></div>\s*<div class="card-grid">(.*?)</div>',
    re.S)


def article_count(d):
    """卡片上的「N 篇」= md 数去掉 00 导读和 _/. 开头的内部稿。"""
    return len([p for p in d.glob("*.md")
                if not p.name.startswith(("00", "_", "."))])


def card_book_title(book):
    """书名里已含《》时内层换成〈〉，避免《马克思与《资本论》》。"""
    return book.replace("《", "〈").replace("》", "〉")


def load_cat_conf():
    """tools/books.json：{"<书目录名>": {"cat": "<部分名>", "desc": "<可选文案>"}}"""
    if CATS_CONF.exists():
        return json.loads(CATS_CONF.read_text(encoding="utf-8"))
    return {}


def sync_catalog(root):
    """根 index.html：给缺卡片的书补卡、重排卡号、刷新统计。返回新增书目。"""
    master = root / "index.html"
    s = master.read_text(encoding="utf-8")
    parts = list(PART_RE.finditer(s))
    if not parts:
        print("catalog: 未找到 part-head/card-grid 结构，跳过")
        return []
    have = set(re.findall(r'href="([^"]+)/index\.html"', s))
    book_dirs = [d for d in sorted(root.iterdir())
                 if d.is_dir() and (d / "index.html").exists()
                 and not d.name.startswith(("_", "."))
                 and article_count(d) > 0]
    missing = [d.name for d in book_dirs if d.name not in have]
    if not missing:
        print("catalog: 卡片齐全")
    conf = load_cat_conf()
    inserts = []          # (pos, text) 统一按位置降序应用
    for name in missing:
        info = conf.get(name, {})
        cat = info.get("cat")
        target = next((p for p in parts if p.group(2) == cat), None)
        if target is None:
            target = parts[-1]
            print(f"catalog: {name} 未在 books.json 配分类，"
                  f"暂放入「{target.group(2)}」，请修正后重跑或手工移动")
        desc = info.get("desc") or S.truncate(S.book_desc(root / name), 130)
        card = CARD_T.format(dir=name, num=0, n=article_count(root / name),
                             title=card_book_title(name), desc=desc)
        inserts.append((target.end(3), card))
        print(f"catalog: +卡片《{name}》 → {target.group(2)}")
    for pos, text in sorted(inserts, reverse=True):
        s = s[:pos] + text + s[pos:]
    # 卡号按文档顺序重排
    total = len(re.findall(r'class="book-card"', s))
    it = iter(range(1, total + 1))
    s = re.sub(r'<span class="card-num">\d+</span>',
               lambda m: f'<span class="card-num">{next(it)}</span>', s)
    # 统计文案
    nb = total
    arts = sum(article_count(root / d.name) for d in book_dirs)
    s = re.sub(r'\d+ 本书', f'{nb} 本书', s, count=1)
    s = re.sub(r'共 \d+ 篇解读', f'共 {arts} 篇解读', s)
    s = re.sub(r'共 \d+ 个系列 · \d+ 篇解读',
               f'共 {nb} 个系列 · {arts} 篇解读', s)
    # 侧栏分类链接附书目数（幂等：先剥掉旧计数再重写）
    cnt = {m.group(2): len(re.findall(r'class="book-card"', m.group(3)))
           for m in PART_RE.finditer(s)}
    id2name = dict(re.findall(r'<h2 id="(g\d+)">([^<]*)</h2>', s))

    def _toc(m):
        name = id2name.get(m.group(1))
        if name is None:
            return m.group(0)
        base = re.sub(r'（\d+）$', '', m.group(2))
        return (f'<a href="#{m.group(1)}" class="lvl-2">'
                f'{base}（{cnt.get(name, 0)}）</a>')

    s = re.sub(r'<a href="#(g\d+)" class="lvl-2">([^<]+)</a>', _toc, s)
    master.write_text(s, encoding="utf-8")
    print(f"catalog: {nb} 本书 · {arts} 篇")
    return missing


def sync_readme(root):
    """README：重建「收录书籍」分类表并同步计数（书目顺序取自 index.html）。"""
    rm = root / "README.md"
    if not rm.exists():
        return
    s = rm.read_text(encoding="utf-8")
    ms = (root / "index.html").read_text(encoding="utf-8")
    rows = []
    nb, arts = 0, 0
    for m in PART_RE.finditer(ms):
        dirs = re.findall(r'href="([^"]+)/index\.html"', m.group(3))
        dirs = [d for d in dirs if (root / d).is_dir()]
        if not dirs:
            continue
        nb += len(dirs)
        arts += sum(article_count(root / d) for d in dirs)
        rows.append(f"| {m.group(2)} | {' · '.join(dirs)} |")
    if not rows:
        return
    table = "| 分类 | 书目 |\n|---|---|\n" + "\n".join(rows)
    s = re.sub(r'\| 分类 \| 书目 \|.*?(?=\n## |\Z)', table + "\n", s, flags=re.S)
    s = re.sub(r'（\d+ 个系列 · \d+ 篇解读）', f'（{nb} 个系列 · {arts} 篇解读）', s)
    s = re.sub(r'共 \d+ 个书籍目录', f'共 {nb} 个书籍目录', s)
    s = re.sub(r'收录书籍（\d+ 本）', f'收录书籍（{nb} 本）', s)
    rm.write_text(s, encoding="utf-8")
    print(f"readme: 收录书籍表 {nb} 本已同步")


def process_book(book, check_only, stats, root=None):
    root = root or ROOT
    prev_seo_root = S.ROOT
    S.ROOT = root
    try:
        return _process_book(book, check_only, stats, root)
    finally:
        S.ROOT = prev_seo_root


def _process_book(book, check_only, stats, root):
    d = root / book
    if not d.is_dir():
        print(f"skip (not a dir): {book}")
        return None
    arts = S.article_files(d)
    idx = d / "index.html"
    if not arts or not idx.exists():
        print(f"skip (no html in): {book}")
        return None
    bdesc = S.truncate(S.book_desc(d))
    sib_rels = [a.relative_to(root) for a in arts]

    targets = [(a, False) for a in arts] + [(idx, True)]
    for path, is_index in targets:
        h = path.read_text(encoding="utf-8")
        missing = [it for it in ITEMS if need(h, it, is_index)]
        if is_index and "NAV-INJECT" in h:
            pass
        for it in missing:
            stats["missing"][it] += 1
        if check_only or not missing:
            for it in (missing if check_only else []):
                stats["files"][str(path.relative_to(root))] = missing
            if not missing:
                stats["ok"] += 1
            continue
        for it in missing:
            if it == "seo":
                continue
            h = apply(h, it, book, is_index)
        if "seo" in missing:
            rel = path.relative_to(root)
            date = doc_date(h)
            if is_index:
                ld = S.ld_book_index(rel, book, bdesc, date, arts)
                h = apply_seo(h, rel, "collection", book, bdesc, date, ld)
            else:
                desc = seo_desc(h, bdesc)
                ld = S.ld_article(rel, S.page_title(h) or path.stem, desc, book, date, sib_rels)
                h = apply_seo(h, rel, "article", book, desc, date, ld)
        path.write_text(h, encoding="utf-8")
        stats["changed"] += 1
        stats["files"][str(path.relative_to(root))] = missing
    return (bdesc, arts)


def all_book_dirs(root):
    return [d.name for d in sorted(root.iterdir())
            if d.is_dir() and (d / "index.html").exists()
            and not d.name.startswith(("_", "."))]


def main():
    ap = argparse.ArgumentParser(description="skill 模板 HTML -> 站点标准形态后处理")
    ap.add_argument("books", nargs="*",
                    help="书目录名，可多个；不指定则处理全部书目录")
    ap.add_argument("--check", action="store_true", help="只检查缺项，不写盘")
    args = ap.parse_args()
    books = args.books or all_book_dirs(ROOT)
    if not books:
        ap.error("没有找到任何含 index.html 的书目录")

    stats = {"changed": 0, "ok": 0, "missing": {it: 0 for it in ITEMS}, "files": {}}
    done = []
    for book in books:
        r = process_book(book, args.check, stats)
        if r:
            done.append((book, r[0], r[1]))
    if args.check:
        print(f"checked books={len(done)} ok={stats['ok']}")
        for it in ITEMS:
            print(f"  missing {it}: {stats['missing'][it]}")
        have = set(re.findall(r'href="([^"]+)/index\.html"',
                              (ROOT / "index.html").read_text(encoding="utf-8")))
        for b in all_book_dirs(ROOT):
            if b not in have and article_count(ROOT / b) > 0:
                print(f"  缺总目录卡片: {b}")
        return

    if done:
        sm = ROOT / "sitemap.xml"
        s = sm.read_text(encoding="utf-8")
        added = 0
        for book, bdesc, arts in done:
            d = ROOT / book
            entries = [(d / "index.html", "0.8")] + [(a, "0.6") for a in arts]
            for p, pr in entries:
                rel = p.relative_to(ROOT)
                loc = S.url_for(rel)
                if loc in s:
                    continue
                h = p.read_text(encoding="utf-8")
                line = (f"  <url><loc>{loc}</loc><lastmod>{doc_date(h)}</lastmod>"
                        f"<priority>{pr}</priority></url>")
                s = s.replace("</urlset>", line + "\n</urlset>")
                added += 1
        if added:
            sm.write_text(s, encoding="utf-8")
        print(f"sitemap +{added} urls")

        master = ROOT / "index.html"
        m = master.read_text(encoding="utf-8")
        book_dirs = [ROOT / b for b in all_book_dirs(ROOT)]
        block = S.build_block(Path("index.html"), "collection",
                              S.page_title(m), DESC_MASTER, doc_date(m),
                              S.ld_master(book_dirs))
        old = m
        m = re.sub(re.escape(S.MARK_S) + r".*?" + re.escape(S.MARK_E) + r"\n?",
                   "", m, flags=re.S)
        m = m.replace("</head>", block + "\n</head>", 1)
        if m != old:
            master.write_text(m, encoding="utf-8")
            print(f"master index JSON-LD books={len(book_dirs)} (updated)")
        else:
            print("master index 无变化")

        sync_catalog(ROOT)
        sync_readme(ROOT)

    print(f"books={len(done)} files_changed={stats['changed']} already_ok={stats['ok']}")


if __name__ == "__main__":
    main()
